package com.collapsar.springboot.model.database;

import java.util.Date;

public class ConfigGlobal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.global_key
     *
     * @mbggenerated
     */
    private String globalKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.global_value
     *
     * @mbggenerated
     */
    private String globalValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_global.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.id
     *
     * @return the value of config_global.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.id
     *
     * @param id the value for config_global.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.create_time
     *
     * @return the value of config_global.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.create_time
     *
     * @param createTime the value for config_global.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.update_time
     *
     * @return the value of config_global.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.update_time
     *
     * @param updateTime the value for config_global.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.global_key
     *
     * @return the value of config_global.global_key
     *
     * @mbggenerated
     */
    public String getGlobalKey() {
        return globalKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.global_key
     *
     * @param globalKey the value for config_global.global_key
     *
     * @mbggenerated
     */
    public void setGlobalKey(String globalKey) {
        this.globalKey = globalKey == null ? null : globalKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.global_value
     *
     * @return the value of config_global.global_value
     *
     * @mbggenerated
     */
    public String getGlobalValue() {
        return globalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.global_value
     *
     * @param globalValue the value for config_global.global_value
     *
     * @mbggenerated
     */
    public void setGlobalValue(String globalValue) {
        this.globalValue = globalValue == null ? null : globalValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_global.remark
     *
     * @return the value of config_global.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_global.remark
     *
     * @param remark the value for config_global.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}