package com.collapsar.springboot.dao.mapper;

import com.collapsar.springboot.model.database.ConfigGlobal;
import com.collapsar.springboot.model.database.ConfigGlobalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigGlobalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int countByExample(ConfigGlobalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigGlobalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int insert(ConfigGlobal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int insertSelective(ConfigGlobal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    List<ConfigGlobal> selectByExample(ConfigGlobalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    ConfigGlobal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigGlobal record, @Param("example") ConfigGlobalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigGlobal record, @Param("example") ConfigGlobalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigGlobal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_global
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigGlobal record);
}